// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/networkmanagement/v1beta1/trace.proto

package com.google.cloud.networkmanagement.v1beta1;

public interface AbortInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.networkmanagement.v1beta1.AbortInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Causes that the analysis is aborted.
   * </pre>
   *
   * <code>.google.cloud.networkmanagement.v1beta1.AbortInfo.Cause cause = 1;</code>
   * @return The enum numeric value on the wire for cause.
   */
  int getCauseValue();
  /**
   * <pre>
   * Causes that the analysis is aborted.
   * </pre>
   *
   * <code>.google.cloud.networkmanagement.v1beta1.AbortInfo.Cause cause = 1;</code>
   * @return The cause.
   */
  com.google.cloud.networkmanagement.v1beta1.AbortInfo.Cause getCause();

  /**
   * <pre>
   * URI of the resource that caused the abort.
   * </pre>
   *
   * <code>string resource_uri = 2;</code>
   * @return The resourceUri.
   */
  java.lang.String getResourceUri();
  /**
   * <pre>
   * URI of the resource that caused the abort.
   * </pre>
   *
   * <code>string resource_uri = 2;</code>
   * @return The bytes for resourceUri.
   */
  com.google.protobuf.ByteString
      getResourceUriBytes();
}
